/* 
# 최초 실행시 캔버스 컷팅값(ON)
preCutting=!0

# 최초 실행시 캔버스 컷팅값(OFF)
preCutting=!1

# 전단컷팅 디폴트값(기준)
PreCuttingLength:12

# 금액 수정(원본) * 수정하지 말것!
var c=a.size.thickness;c=6>c?700:6<=c&&12>=c?1E3:13<=c&&18>=c?1500:2000

설명:
	두께가 6보다 작으면 700원
	두께가 6이상이거나 12이하면 1000원(1E3)
	두께가 13이상이거나 18이하면 1500원
	그 외: 2000원

*/

(function(){function C(a){this.id=Y();this.name=a;this.size=c.defaultWoodSize;this.preCutting=!1;this.copyNum=1;this.cuttingNum=0}function Z(){c.watch("cuttingNum",function(a,b,c){a=w();a.cuttingNum=c;$("#cutting-num").html(c);$("#cutting-cost").html(F(a).addThousandComma());O();return c});c.watch("editCanvasMode",function(a,b,d){q();!0===d?c.woodLayer&&c.woodLayer.find(".wood-group,.cutting-edge").each(function(a,b){a.listening(!1)}):(c.woodLayer&&c.woodLayer.find(".wood-group,.cutting-edge").each(function(a,
  b){a.listening(!0)}),c.stage.container().style.cursor="default");return d});c.watch("moveCanvasMode",function(a,b,d){!0===d?($("#move-canvas").addClass("active"),c.stage.container().style.cursor="move"):($("#move-canvas").removeClass("active"),c.stage.container().style.cursor="default");return d})}function aa(){function a(a,b,d){["width","height","thickness"].forEach(function(b){a[b]||(a[b]=c.defaultWoodSize[b])});d.deleteNodes();d.preCutting=b;c.init(d.id,a);alertify.success("\ud06c\uae30\uac00 \ubcc0\uacbd\ub418\uc5c8\uc2b5\ub2c8\ub2e4.")}
  function b(a,b){var d={width:2560,height:1440},g=P(d,a.size);c.woodLayer.scale({x:g,y:g});c.stage.position({x:0,y:0});c.stage.size(d);c.backLayer.hide();var e=new Konva.Rect({x:0,y:0,width:d.width,height:d.height,fill:"white",id:"print-back"}),f="\ubaa9\uc7ac \ud06c\uae30 : "+Q(a),k="\uc804\ub2e8 \ucef7\ud305 \uc5ec\ubd80 : ";k=a.preCutting?k+"O":k+"X";f=function(a){a=a.map(function(a){return new Konva.Text({text:a,fontSize:30,fill:"black",align:"center",y:15})});var b=a.map(function(a){return new Konva.Line({y:4,
  points:[0,0,0,56],strokeWidth:4,stroke:"black"})}),c;for(c=0;c<a.length;c++){var d=15,g=0;for(g=0;g<c;g++)d+=a[g].getTextWidth()+40;a[c].x(d);a[c].width(a[c].width()+40);b[c].x(d)}c=a[a.length-1];d=new Konva.Line({x:c.x()+c.width(),y:4,points:[0,0,0,56],strokeWidth:4,stroke:"black"});b.push(d);d=new Konva.Line({y:60,x:0,points:[15,0,c.x()+c.width(),0],strokeWidth:4,stroke:"black"});b.push(d);c=new Konva.Line({y:4,x:0,points:[15,0,c.x()+c.width(),0],strokeWidth:4,stroke:"black"});b.push(c);return a.concat(b)}([a.name,
  f,k,"\ucef7\ud305\uc218 : "+c.cuttingNum,"\uc7a5\uc218 : "+a.copyNum,"* \uac00\ub85c 70\ubbf8\ub9cc \uc774\uba70, \uc138\ub85c 60\ubbf8\ub9cc \uc870\uac01\uc740 \ubc88\ud638 \ucd9c\ub825 \uc548\ub428"]);var u=new Konva.Layer({id:"print-back-layer"});c.stage.add(u);u.add(e);f.forEach(function(a){u.add(a)});u.moveToBottom();e=function(){function a(a,b){if(!a||!b)return!1;var c=a.getWood(),d=b.getWood();return a.x()+c.width()+h.CuttingEdge.width===b.x()&&a.y()===b.y()&&Number(c.width())===Number(d.width())&&
  Number(c.height())===Number(d.height())}var b=c.woodLayer.find(".wood-group").toArray().filter(function(a){return a.getAttr("required")}),d=b.slice();b.sort(function(a,b){var c=Number(a.x()),d=Number(a.y()),g=Number(b.x()),e=Number(b.y());return c-g||d-e});d.sort(function(a,b){var c=Number(a.x()),d=Number(a.y()),g=Number(b.x()),e=Number(b.y());return d-e||c-g});var g=[],e=[];d.forEach(function(b,c){if(!e.includes(c)){var f=1,n=[b];for(e.push(c);a(d[c+f-1],d[c+f]);)e.push(c+f),n.push(d[c+f]),f++;1<
  n.length&&g.push(n)}});var f=[].concat.apply([],g),n=[];b.forEach(function(a,b){if(!n.includes(a))if(f.includes(a)){var c=g.find(function(b){return b.includes(a)});n=n.concat(c)}else n.push(a)});return n.map(function(a,b){var c=a.getWood(),d=a.getCenterPosition();d.x-=15;d.y-=15;var g=Number(c.width());c=Number(c.height());if(70>=g&&60>=c)return null;if(100>=g&&100>=c)d.x=a.x()+g-30-2,d.y=a.y()+c-30-2;else if(100>=g)d.y=a.y()+3*c/4;else if(100>=c)d.x=a.x()+3*g/4;else if(200>=g||140>=c)d.x=a.x()+2*
  g/3,d.y=a.y()+2*c/3;d=new Konva.Group({name:"label-group",x:d.x,y:d.y});g=new Konva.Circle({x:15,y:15,radius:15,fill:"black"});c=new Konva.Text({y:5.5,text:b+1,fontSize:20,fill:"white",width:30,align:"center"});d.add(g).add(c);return d}).filter(function(a){return null!=a})}();var v=new Konva.Layer({id:"print-front-layer"});c.stage.add(v);e.forEach(function(a){v.add(a)});v.moveToTop();v.scale({x:g,y:g});c.stage.draw();g={x:0,y:0,width:d.width,height:d.height,quality:1};browser.startsWith("ie")?(d=
  function(a){a=atob(a.split(",")[1]);for(var c=[],b=0;b<a.length;b++)c.push(a.charCodeAt(b));return new Blob([new Uint8Array(c)],{type:"image/png"})},window.navigator.msSaveBlob?(g=c.stage.toDataURL(g),d=d(g),window.navigator.msSaveBlob(d,a.name+".png")):window.document.execCommand&&(d='          <html>           <head>           </head>           <body>           <img src="'+c.stage.toDataURL(g)+'" border="0">           </body>           </html>          ',window.open().document.write(d))):(d=c.stage.toDataURL(g),
  g=document.createElement("a"),g.setAttribute("download",a.name+".png"),g.setAttribute("href",d.replace("image/png","image/octet-stream")),g.click());c.backLayer.show();c.stage.find("#print-back-layer").destroy();c.stage.find("#print-front-layer").destroy();b&&b()}function d(a){a.preventDefault();a=$(this).attr("work-id");a!==c.workId&&(w().save(),e(a))}function e(a){var b=r[a];if(!b)throw Error("Can not find work");var d=Object.assign({},b.size);b.preCutting&&(d.width+=h.PreCuttingLength,d.height+=
  h.PreCuttingLength);c.init(a,d);return b}$(".btn").mouseup(function(){$(this).blur()});$(".standard-wood-size").click(function(b){alertify.confirm("\ubaa9\ucde8\ub3c4 \ud06c\uae30\ub97c \ubc14\uafb8\uc2dc\uaca0\uc5b4\uc694? \ud604\uc7ac \ubaa9\ucde8\ub3c4\uc758 \ucef7\ud305\uc740 \uc9c0\uc6cc\uc9d1\ub2c8\ub2e4.",function(){var c=b.target,d=$(c).attr("wood-width"),g=$(c).attr("wood-height");c=$(c).attr("wood-thickness");d={width:d,height:g,thickness:c};g=$("#pre-cutting").prop("checked");c=w();a(d,
  g,c)},z)});$("#edit-work-name").click(R());$("#product-resize").click(function(){alertify.confirm("\ubaa9\ucde8\ub3c4 \ud06c\uae30\ub97c \ubc14\uafb8\uc2dc\uaca0\uc5b4\uc694? \ud604\uc7ac \ubaa9\ucde8\ub3c4\uc758 \ucef7\ud305\uc740 \uc9c0\uc6cc\uc9d1\ub2c8\ub2e4.",function(){var c={width:$("#wood-width").val(),height:$("#wood-height").val(),thickness:$("#wood-thickness").val()},b=$("#pre-cutting").prop("checked"),d=w();a(c,b,d)},z)});$("#zoom-in").click(function(){q();var a=c.scale*=1.1;c.woodLayer.scale({x:a,
  y:a});c.backLayer.scale({x:a,y:a});c.stage.draw()});$("#zoom-out").click(function(){q();var a=c.scale*=.9;c.woodLayer.scale({x:a,y:a});c.backLayer.scale({x:a,y:a});c.stage.draw()});$("#move-canvas").click(function(){q();c.editCanvasMode=!c.editCanvasMode;c.moveCanvasMode=!c.moveCanvasMode;c.stage.draggable(!c.stage.draggable());ca();c.woodLayer.draw()});$("#initialize-canvas").click(function(){alertify.confirm("\ud604\uc7ac \ubaa9\ucde8\ub3c4\ub97c \ucd08\uae30\ud654 \ud558\uc2dc\uaca0\uc5b4\uc694? \ucef7\ud305\ub3c4 \uc9c0\uc6cc\uc9d1\ub2c8\ub2e4.",
  function(){var a=w();a.deleteNodes();e(a.id);alertify.success("\ucd08\uae30\ud654 \ub418\uc5c8\uc2b5\ub2c8\ub2e4.")},z)});$("#save-to-file").click(function(){q();var a=w();a.save();S(a).success?(b(a),e(a.id)):alertify.alert('<span class="text-danger">\ucd5c\uc18c\ud55c \ud55c\uac1c \uc774\uc0c1\uc758 \ud544\uc218 \uc870\uac01\uc744 \uc9c0\uc815\ud574\uc57c \ud569\ub2c8\ub2e4.</span>')});$("#all-save-to-file").click(function(){q();var a=w();a.save();var c=Object.keys(r).map(function(a){return S(r[a])}).filter(function(a){return!a.success}).map(function(a){return a.workName});
  0<c.length?alertify.alert('<span class="text-danger">\ucd5c\uc18c\ud55c \ud55c\uac1c \uc774\uc0c1\uc758 \ud544\uc218 \uc870\uac01\uc744 \uc9c0\uc815\ud574\uc57c \ud569\ub2c8\ub2e4.</span> <br/>\ub2e4\uc74c \ubaa9\ucde8\ub3c4\ub294 \ud544\uc218 \uc870\uac01\uc774 \uc9c0\uc815\ub418\uc5b4\uc788\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4. <br/>'+c.join()):(f={currentWorkId:a.id},$("#all-save-waiting-modal").modal({keyboard:!1}))});var f={};$("#all-save-waiting-modal").on("shown.bs.modal",function(a){var c=this,
  d=Object.keys(r),g=0;(function l(){var a=d[g];a?(a=e(a),g+=1,b(a,l)):$(c).modal("hide")})()});$("#all-save-waiting-modal").on("hidden.bs.modal",function(a){f.hasOwnProperty("currentWorkId")&&e(f.currentWorkId)});$("#total-cutting-cost-button").click(function(a){function c(a,c){var d=b();c&&d.addClass("active");a.forEach(function(a){c?d.append($('<th class="text-center">'+a+"</th>")):d.append($('<td class="text-center">'+a+"</td>"))});return d}function b(){return $('<tr class="total-cutting-cost-row"></tr>')}
  var d=$("#total-cutting-cost-content-table");$("tr",d).remove();a=c("# \uc774\ub984 \ud06c\uae30 \uc804\ub2e8\ucef7\ud305 \ucef7\ud305\uc218 \uc7ac\ub2e8\ube44 \uc7a5 \uc7ac\ub2e8\ube44*\uc7a5".split(" "),!0);d.append(a);var g=0;Object.keys(r).forEach(function(a,b){var e=r[a],f=b+1,n=e.name,l=Q(e),m=e.preCutting?"O":"X",k=e.cuttingNum,h=F(e,!1).addThousandComma()+"\uc6d0",ba=e.copyNum;e=F(e,!0);g+=e;e=e.addThousandComma()+"\uc6d0";f=c([f,n,l,m,k,h,ba,e]);f.hide();d.append(f)});a=function(a){var c=
  b();c.append($('<td colspan="7" class="text-right"><h5>\ucd1d\ud569</h5></td>'));c.append($('<td class="text-center"><h5>'+a+"</h5></td>"));c.addClass("info");return c}(g.addThousandComma()+"\uc6d0");a.hide();d.append(a);$("#total-cutting-cost-modal").modal();$("#total-cutting-cost-modal").on("shown.bs.modal",function(){$("tr",d).each(function(a){$(this).fadeIn(400)})})});$(".work-list-item").click(d);$("#add-work").click(function(){if(Object.keys(r).length>=h.MaxWorkNum)alertify.alert("\ubaa9\ucde8\ub3c4\ub294 "+
  h.MaxWorkNum+"\uac1c \uae4c\uc9c0\ub9cc \ub9cc\ub4e4 \uc218 \uc788\uc2b5\ub2c8\ub2e4.");else{c.lastWorkNum++;var a=new C("\ubaa9\ucde8\ub3c4"+c.lastWorkNum);r[a.id]=a;a=T(a);$("#work-list").append(a);a.on("click",d)}});$("#delete-work").click(function(){alertify.confirm("\ud604\uc7ac \ubaa9\ucde8\ub3c4\ub97c \uc0ad\uc81c\ud558\uc2dc\uaca0\uc2b5\ub2c8\uae4c?",function(){if(Object.keys(r).length<=h.MinWorkNum)alertify.alert("\ubaa9\ucde8\ub3c4\ub294 \ucd5c\uc18c "+h.MinWorkNum+"\uac1c \uc774\uc0c1\uc774\uc5b4\uc57c \ud569\ub2c8\ub2e4.");
  else{w().deleteNodes();delete r[c.workId];var a=$(".work-list-item[work-id="+c.workId+"]"),b=a.prev();0===b.length&&(b=a.next());a.remove();a=b.attr("work-id");e(a);alertify.success("\uc0ad\uc81c\ub418\uc5c8\uc2b5\ub2c8\ub2e4.")}},z)});$("#main").keydown(function(a){c.selectedEdge&&(37===a.keyCode||38===a.keyCode?c.selectedEdge.move1Step(-1):(39===a.keyCode||40===a.keyCode)&&c.selectedEdge.move1Step(1))})}function L(a){var b=a.getWood();a.on("mouseenter",function(){a.fillActiveColor();c.woodLayer.draw()});
  a.on("mouseleave",function(){a.fillDefaultColor();c.woodLayer.draw()});a.on("click",function(d){H();d=c.stage.getAdjustedPointerPosition();da(d,a,b)})}function I(a){function b(a){var b=Math.floor(a.target.x());void 0!==b&&null!==b&&(g.forEach(function(a,c){var d=a.getWood(),e=y[a._id].getWood();d.width(e.width()+b);a.updateLabels()}),k.forEach(function(a,c){var d=a.getWood(),e=u[a._id],f=e.getWood();d.width(f.width()-b);a.x(e.x()+b);a.updateLabels()}),p.forEach(function(a,c){var d=a.points();d[2]=
  B[a._id].points()[2]+b;a.points(d)}),n.forEach(function(a,c){var d=a.points();d[0]=t[a._id].points()[0]+b;a.points(d)}),c.woodLayer.draw())}function d(a){var b=Math.floor(a.target.y());void 0!==b&&null!==b&&(g.forEach(function(a,c){var d=a.getWood(),e=y[a._id].getWood();d.height(e.height()+b);a.updateLabels()}),k.forEach(function(a,c){var d=a.getWood(),e=u[a._id],f=e.getWood();d.height(f.height()-b);a.y(e.y()+b);a.updateLabels()}),p.forEach(function(a,c){var d=a.points();d[3]=B[a._id].points()[3]+
  b;a.points(d)}),n.forEach(function(a,c){var d=a.points();d[1]=t[a._id].points()[1]+b;a.points(d)}),c.woodLayer.draw())}var e=h.EdgeType,f=a.hasName("vertical-edge")?e.v:e.h;a.on("click",function(b){b=c.stage.getAdjustedPointerPosition();ea(b,a);fa(this)});a.on("mouseenter",function(b){c.selectedEdge||(c.stage.container().style.cursor=f===e.v?"col-resize":"row-resize");a.styleActiveColor();c.woodLayer.draw()});a.on("mouseleave",function(b){c.selectedEdge?a.isSelected()||(a.styleDefaultColor(),c.woodLayer.draw()):
  (c.stage.container().style.cursor="default",a.styleDefaultColor(),c.woodLayer.draw())});a.hitFunc(function(b){b.beginPath();var c=a.points();if(f===e.v){var d=c[0]-10;var g=c[1];var n=20;var l=c[3]-g}else f===e.h&&(d=c[0],g=c[1]-10,n=c[2]-d,l=20);b.rect(d,g,n,l);b.closePath();b.fillStrokeShape(this)});var g,k,p,n,m,l,y,u,v,B,t;a.on("dragstart",function(b){function d(a){var b=Math.max(c.woodSize.width,c.woodSize.height)/400;return(f===e.v?Number(a.width())-h.CuttingBound-b:Number(a.height())-h.CuttingBound-
  b)*c.scale}q();b=a.findAllAdjacents();g=b.woodGroups1;k=b.woodGroups2;y={};g.forEach(function(a){y[a._id]=a.clone()});u={};k.forEach(function(a){u[a._id]=a.clone()});v=a.clone();p=b.edges1;n=b.edges2;B={};p.forEach(function(a){B[a._id]=a.clone()});t={};n.forEach(function(a){t[a._id]=a.clone()});testing&&(console.log(g),console.log(k),console.log(y),console.log(u));if(testing){b=function(a){var b=a.points();console.log("id",a._id,"start ("+b[0]+", "+b[1]+") end ("+b[2]+", "+b[3]+")")};var G=function(a){var b=
  a.getWood();console.log("id",a._id,"position",a.position(),"width",b.width(),"height",b.height())};console.log(" ");console.log("edge clicked!",a);console.log("woodGroups1",g);g.forEach(G);console.log("woodGroups2",k);k.forEach(G);console.log("edges1",p);p.forEach(b);console.log("edges2",n);n.forEach(b)}g.sort(function(a,b){return f===e.v?a.x()-b.x():a.y()-b.y()});k.sort(function(a,b){if(f===e.v){var c=a.getWood(),d=b.getWood();return a.x()+c.width()-(b.x()+d.width())}c=a.getWood();d=b.getWood();
  return a.y()+c.height()-(b.y()+d.height())});b=k[0];G=g[g.length-1].getWood();m=-d(G);m=f===e.v?m+c.stage.x():m+c.stage.y();m=Math.ceil(m);b=b.getWood();l=d(b);l=f===e.v?l+c.stage.x():l+c.stage.y();l=Math.ceil(l);f===e.v?a.dragBoundFunc(function(a){var b;a.x>=m&&a.x<=l?b=a.x:a.x<m?b=m:a.x>l&&(b=l);return{x:b,y:this.getAbsolutePosition().y}}):a.dragBoundFunc(function(a){var b;a.y>=m&&a.y<=l?b=a.y:a.y<m?b=m:a.y>l&&(b=l);return{x:this.getAbsolutePosition().x,y:b}})});if(f===e.v)a.on("dragmove",b);else a.on("dragmove",
  d);a.on("dragend",function(b){function d(a){a=a.getWood();return D(a.size())}if(c.selectedEdge)if(a.isSelected())H();else return;b=g.every(d);var l=k.every(d);if(b&&l)b=k[0],b.getWood(),l=f===e.v?b.x():b.y(),l-=h.CuttingEdge.width/2,b=a.points(),f===e.v?(b[0]=l,b[2]=l):(b[1]=l,b[3]=l),a.x(0),a.y(0);else{b=function(a,b){a.remove()};l=function(a){Object.keys(a).map(function(b){b=a[b];I(b);c.woodLayer.add(b)})};var m=function(a){Object.keys(a).map(function(b){b=a[b];L(b);c.woodLayer.add(b)})};m(y);m(u);
  l(B);l(t);l=Object.keys(u)[0];l=u[l];l=f===e.v?l.x():l.y();l-=h.CuttingEdge.width/2;m=v.points();f===e.v?(m[0]=l,m[2]=l):(m[1]=l,m[3]=l);v.x(0);v.y(0);c.woodLayer.add(v);console.log(g);console.log(k);console.log(y);console.log(u);console.log(B);console.log(t);g.forEach(b);k.forEach(b);p.forEach(b);n.forEach(b);a.destroy();I(v);v.styleDefaultColor();J()}c.woodLayer.draw()})}function ha(a){a.on("mouseenter",function(a){$("#main").is(":focus")||$("#main").focus()})}function T(a){var b=$('      <button class="button work-list-item list-group-item" type="button">        <div class="work-list-item-name">          <span></span>          <a class="edit-work-list-item-name-button" href="#">            <span class="glyphicon glyphicon-pencil"></span>          </a>        </div>         <div class="work-copy">          <input type="number" class="work-copy-number" min="1" max="999" maxlength="3" value="1" onkeypress="if(this.value.length > 2) return false;" onchange="if(this.value > 999) {this.value = 999} else if(!this.value || this.value < 1) {this.value = 1}"></input>          <label for="">\uc7a5</label>        </div>      </button>');
  b.attr("work-id",a.id);$(".work-list-item-name > span",b).html(a.name);$(".edit-work-list-item-name-button",b).click(R(a.id));$(".work-copy-number",b).on("change textInput input paste keypress",function(){var b=$(this).val();999<b?alertify.error("\ud55c \ubaa9\ucde8\ub3c4\uc758 \ucd5c\ub300 \uc7a5\uc218\ub294 999\uc7a5 \uc785\ub2c8\ub2e4"):(a.copyNum=b,O())});return b}function ia(a,b){function c(a,b,c,d){return new Konva.Line({points:[a,b,c,d],stroke:"#888888",strokeWidth:.6})}var e=new Konva.Group({id:"grid"}),
  f=a,g=a;for(f;f<h.Canvas.size.width/b;f+=a){var k=c(f,0,f,h.Canvas.size.height/b);e.add(k)}for(g;g<h.Canvas.size.height/b;g+=a)f=c(0,g,h.Canvas.size.width/b,g),e.add(f);return e}function A(a,b){var c=a.x,e=a.y,f=b.width,g=b.height;if(0>f||0>g)throw Error("Size must be positive integer");c=new Konva.Group({x:c,y:e,name:"wood-group"});c.setAttr("required",!1);f=new Konva.Rect({width:f,height:g,name:"wood",fill:h.Wood.color["default"],stroke:"black",strokeWidth:1,opacity:h.Wood.opacity});g=U(f);c.add(f).add(g.w).add(g.h);
  L(c);return c}function U(a){function b(a){var b="width"===a?"center":"height"===a?"left":void 0;return function(d,e,f){var g=1E3<Math.max(c.woodSize.width,c.woodSize.height)?50>f?24:-11.7+9.25*Math.log(f):50>f?16.5:-.959+4.483*Math.log(f);var n=30<=g?8.9:10>=g?3.5:-.811+.27*g;d=new Konva.Text({x:d,y:e,name:"wood-label",text:f,width:"auto",height:"auto",fontSize:g,align:b});"width"===a?(d.y(d.y()+n),d.x(d.x()-d.width()/2)):"height"===a&&(d.x(d.x()+n),d.y(d.y()-d.height()/2));f<h.LengthLabelInverseLimitLength&&
  ("width"===a?d.y(d.y()-d.height()-2*n):"height"===a&&d.x(d.x()-d.width()-2*n));return d}}var d=a.x()+a.width()/2,e=a.y(),f=a.x(),g=a.y()+a.height()/2,k=b("width"),p=b("height");d=k(d,e,a.width());a=p(f,g,a.height());return{w:d,h:a}}function K(a,b){var c=new Konva.Line({points:[a.x,a.y,b.x,b.y],name:"cutting-edge",strokeWidth:h.CuttingEdge.strokeWidth,draggable:!0,dragDistance:1});a.x===b.x&&c.addName("vertical-edge");a.y===b.y&&c.addName("horizontal-edge");I(c);return c}function V(a,b){var d=new Konva.Group({x:a.x,
  y:a.y,id:"menu-container-group"}),e=new Konva.Circle({radius:2,fill:"red"}),f=new Konva.Group({x:3,y:3});b.forEach(function(a,b){f.add(a);a.move({x:0,y:27*b})});d.add(e).add(f);f.on("mouseenter",function(a){c.stage.container().style.cursor="pointer"});f.on("mouseleave",function(a){c.stage.container().style.cursor="default"});return d}function x(a,b){var c=new Konva.Group({}),e=new Konva.Rect({width:90,height:27,name:a,fill:"lightgray",stroke:"black",strokeWidth:1}),f=new Konva.Text({width:90,padding:5,
  text:b,fontSize:15,align:"center"});c.on("mouseenter",function(){e.fill("gray");f.fill("white");c.draw()});c.on("mouseleave",function(){e.fill("lightgray");f.fill("black");c.draw()});c.add(e).add(f);return c}function ca(){c.woodLayer.find(".wood-group").each(function(a,b){a.fillDefaultColor()})}function q(){c.moveCanvasMode||(c.stage.container().style.cursor="default");var a=c.interactionLayer.findOne("#menu-container-group");a&&(a.destroy(),c.interactionLayer.draw())}function ea(a,b){q();var d=x("delete-cutting-edge",
  "\ucef7\ud305 \uc0ad\uc81c"),e=x("cancelMenu","\ucde8\uc18c"),f=V(a,[d,e]);d.on("click",function(){q();H();b.deleteEdge()});e.on("click",function(){q();H();b.styleDefaultColor();b.draw();var a=c.stage.getAdjustedPointerPosition();if(a=c.stage.getIntersection(a,".wood-group"))a.fillActiveColor(),a.draw()});f.on("mouseenter",function(a){b.isSelected()||(b.styleActiveColor(),b.draw())});f.on("mouseleave",function(a){b.isSelected()||(b.styleDefaultColor(),b.draw())});c.interactionLayer.add(f);c.interactionLayer.draw()}
  function da(a,b,d){q();var e=x("horizontal-cut","\uac00\ub85c \ucef7\ud305"),f=x("vertical-cut","\uc138\ub85c \ucef7\ud305"),g=x("horizontal-divide","\uac00\ub85c \ubd84\ud560"),h=x("vertical-divide","\uc138\ub85c \ubd84\ud560"),p=b.getAttr("required")?"\uc9c0\uc815 \ud574\uc81c":"\ud544\uc218 \uc9c0\uc815";p=x("set-required-wood",p);var n=x("cancel-menu","\ucde8\uc18c"),m=V(a,[e,f,g,h,p,n]);e.on("click",function(){b.horizontalCut(a);q()});f.on("click",function(){b.verticalCut(a);q()});g.on("click",
  function(){q();var a="{0} {1}mm\uc758 \ub098\ubb34\uc870\uac01\uc744 \uc120\ud0dd\ud558\uc168\uc2b5\ub2c8\ub2e4. \ubd84\ud560\ud560 \ub098\ubb34\ub4e4\uc758 {2}\ub97c \ub098\uc5f4\ud574\uc8fc\uc138\uc694. <br/>\uc794\uc5ec\uc870\uac01\uc758 {3}\ub294 \uc790\ub3d9\uacc4\uc0b0\ub418\uc5b4 \uc0dd\uc131\ub429\ub2c8\ub2e4. \uc774\ud574\uac00 \uc798 \uc548\uac00\uc2dc\uba74 \uc2dc\ud5d8\uc0bc\uc544 \uc22b\uc790\ub97c \ub123\uc5b4\ubcf4\uc154\ub3c4 \uc88b\uc544\uc694.<br/>\uc6081: 50,50 &nbsp &nbsp &nbsp   \uc6082: 50*2,70".format("\uc138\ub85c\uae38\uc774",
  d.height(),"\ub192\uc774","\ub192\uc774");alertify.defaultValue("").prompt(a,function(a,c){try{var e=W(a),f=X(e,d.height());b.horizontalDivide(f);alertify.success("\uac00\ub85c \ubd84\ud560\uc774 \uc644\ub8cc\ub418\uc5c8\uc2b5\ub2c8\ub2e4.")}catch(t){"CustomError"===t.name?alertify.alert(t.message):(console.error(t),alertify.alert("\uc608\uae30\uce58 \ubabb\ud55c \ubb38\uc81c\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."))}},z)});h.on("click",function(){q();var a="{0} {1}mm\uc758 \ub098\ubb34\uc870\uac01\uc744 \uc120\ud0dd\ud558\uc168\uc2b5\ub2c8\ub2e4. \ubd84\ud560\ud560 \ub098\ubb34\ub4e4\uc758 {2}\ub97c \ub098\uc5f4\ud574\uc8fc\uc138\uc694. <br/>\uc794\uc5ec\uc870\uac01\uc758 {3}\ub294 \uc790\ub3d9\uacc4\uc0b0\ub418\uc5b4 \uc0dd\uc131\ub429\ub2c8\ub2e4. \uc774\ud574\uac00 \uc798 \uc548\uac00\uc2dc\uba74 \uc2dc\ud5d8\uc0bc\uc544 \uc22b\uc790\ub97c \ub123\uc5b4\ubcf4\uc154\ub3c4 \uc88b\uc544\uc694.<br/>\uc6081: 50,50 &nbsp &nbsp &nbsp   \uc6082: 50*2,70".format("\uac00\ub85c\uae38\uc774",
  d.width(),"\ub108\ube44","\ub108\ube44");alertify.defaultValue("").prompt(a,function(a,c){try{var e=W(a),f=X(e,d.width());b.verticalDivide(f);alertify.success("\uac00\ub85c \ubd84\ud560\uc774 \uc644\ub8cc\ub418\uc5c8\uc2b5\ub2c8\ub2e4.")}catch(t){"CustomError"===t.name?alertify.alert(t.message):(console.error(t),alertify.alert("\uc608\uae30\uce58 \ubabb\ud55c \ubb38\uc81c\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."))}},z)});p.on("click",function(){q();var a=b.getAttr("required");b.setAttr("required",
  !a);b.fillDefaultColor();b.draw()});n.on("click",function(){q();var a=c.stage.getAdjustedPointerPosition();a=c.stage.getIntersection(a,".wood-group");a||(b.fillDefaultColor(),b.draw());a&&b._id!==a._id&&(b.fillDefaultColor(),a.fillActiveColor(),b.draw(),a.draw())});m.on("mouseenter",function(a){b.fillActiveColor();c.woodLayer.draw()});m.on("mouseleave",function(a){b.fillDefaultColor();c.stage.container().style.cursor="default";c.woodLayer.draw()});c.interactionLayer.add(m);c.interactionLayer.draw()}
  function D(a){return a.width>=h.CuttingBound&&a.height>=h.CuttingBound}function F(a,b){var c=a.size.thickness;c=6>c?1000:6<=c&&12>=c?1E3:13<=c&&23>=c?1500:2000;return b?c*a.cuttingNum*a.copyNum:c*a.cuttingNum}function O(){var a=0,b;for(b in r)a+=F(r[b],!0);$("#total-cutting-cost").html(a.addThousandComma())}function fa(a){if(!a.isSelected()){var b=c.selectedEdge;b&&b.styleDefaultColor();c.selectedEdge=a;a.styleActiveColor();c.woodLayer.find(".cutting-edge").each(function(b,c){b._id!==a._id&&b.listening(!1)});c.woodLayer.draw()}}
  function H(){var a=c.selectedEdge;a&&(a.styleDefaultColor(),c.selectedEdge=null,c.woodLayer.draw());c.woodLayer.find(".cutting-edge").each(function(a,c){a.listening(!0)})}function ja(a,b){var d=h.EdgeType,e=c.interactionLayer.findOne("#menu-container-group");e&&(b===d.v?e.x(e.x()+a*c.scale):b===d.h&&e.y(e.y()+a*c.scale),c.interactionLayer.draw())}function P(a,b){var c=a.height/a.width,e=b.height/b.width;return.9*(c>e?a.width:a.height)/(c>e?b.width:b.height)}function M(a,b){b||(b=window.location.href);
  a=a.replace(/[\[\]]/g,"\\$&");var c=(new RegExp("[?&]"+a+"(=([^&#]*)|&|#|$)")).exec(b);return c?c[2]?decodeURIComponent(c[2].replace(/\+/g," ")):"":null}function E(a,b){if(a){var c;switch(Object.prototype.toString.call(a).slice(8,-1)){case "Object":var e=Object.keys(a);var f={};for(c=0;c<e.length;c++)f[e[c]]=E(a[e[c]],b);return f;case "Array":f=[];for(c=0;c<a.length;c++)f.push(E(a[c]),b);return f;case "Number":return b&&Number.isInteger(b)?(f=Math.pow(10,b),Math.floor(a*f)/f):Math.floor(a);default:return a}}}
  function Y(){function a(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)}return a()+a()+"-"+a()+"-"+a()+"-"+a()+"-"+a()+a()+a()}function w(){var a=r[c.workId];if(!a)throw Error("Can not find work");return a}function J(){alertify.error("\ud55c \ubaa8\uc11c\ub9ac\uc758 \ucd5c\uc18c \uae38\uc774\ub294 "+h.CuttingBound+" \uc774\uc0c1\uc774\uc5b4\uc57c \ud569\ub2c8\ub2e4")}function z(a){alertify.error("\ucde8\uc18c\ub418\uc5c8\uc2b5\ub2c8\ub2e4.")}function Q(a){var b=a.size.width,
  c=a.size.height;a.preCutting&&(b+=h.PreCuttingLength,c+=h.PreCuttingLength);return a.size.thickness&&0<a.size.thickness?a.size.thickness+"T x "+b+" x "+c:b+" x "+c}function S(a){var b=a.getSavedNodes();if(!b)return{success:!1,workName:a.name};b=Konva.Node.create(b);var c=b.find(".wood-group").toArray().filter(function(a){return a.getAttr("required")});b.destroy();return 0<c.length?{success:!0}:{success:!1,workName:a.name}}function W(a){var b=/^(\d+)\*(\d+)$/,c=[];a.split(",").forEach(function(a){a=
  a.trim();if(b.test(a)){var d=a.match(b);a=Number(d[1]);if(0<a){d=d[2];var e;for(e=0;e<d;e++)c.push(a)}}else if(Number.isInteger(Number(a)))a=Number(a),0<a&&c.push(a);else if(""!==a)throw new N("\uc62c\ubc14\ub974\uc9c0 \ubabb\ud55c \uac12\uc785\ub2c8\ub2e4.\n\uc624\ub958 \uac12: "+a);});return c}function X(a,b){var c=a.reduce(function(a,b){return a+b+h.CuttingEdge.width},0),e=b-c;if(0!==e&&e<h.CuttingBound)throw new N("\ud604\uc7ac \uc785\ub825\ub41c \uc22b\uc790\ub4e4\uacfc \ud1b1\ub0a0 \uac04\uaca9\ub4e4\uc744 \ub354\ud55c \uac12\uc774 \ucd5c\ub300\uac12\uc744 \ucd08\uacfc\ud569\ub2c8\ub2e4.\n\uc785\ub825\uac12 \ud569\uacc4: "+
  c);e>=h.CuttingBound&&a.push(e);var f;if(!a.every(function(a){if(a>=h.CuttingBound)return!0;f=a;return!1}))throw new N("\uc785\ub825\ud55c \uc870\uac01\uc758 \ubaa8\ub4e0 \ubaa8\uc11c\ub9ac \uae38\uc774\ub294 "+h.CuttingBound+"mm \uc774\uc0c1\uc774\uc5b4\uc57c \ud569\ub2c8\ub2e4.\n\uc624\ub958\uac12: "+f);return a}function N(a){this.message=a;this.name="CustomError"}function R(a){return function(b){function c(a,b){a.name=b;$("#work-name").html(b);$(".work-list-item").each(function(c){c=$(this);c.attr("work-id")===
  a.id&&$(".work-list-item-name > span",c).html(b)})}b.preventDefault();var e=a?r[a]:w();alertify.defaultValue(e.name).prompt("\uc0c8 \ubaa9\ucde8\ub3c4 \uc774\ub984\uc744 \uc785\ub825\ud574\uc8fc\uc138\uc694",function(a,b){a&&0<a.length?30<a.length?alertify.error("\uc774\ub984\uc774 \ub108\ubb34 \uae41\ub2c8\ub2e4. 30\uc790 \uc774\ud558\ub85c \ud574\uc8fc\uc138\uc694."):(c(e,a),alertify.success("\uc774\ub984\uc774 \ubcc0\uacbd\ub418\uc5c8\uc2b5\ub2c8\ub2e4.")):alertify.error("\uc774\ub984\uc744 \uc785\ub825\ud574\uc8fc\uc138\uc694.")},
  z)}}var r={};C.prototype.deleteNodes=function(){localStorage.removeItem("wood-work/"+this.id)};C.prototype.save=function(){var a=c.woodLayer.toJSON();localStorage.setItem("wood-work/"+this.id,JSON.stringify(a))};C.prototype.getSavedNodes=function(){var a=localStorage.getItem("wood-work/"+this.id);return JSON.parse(a)};var c={},h={Wood:{color:{"default":"#c9c8c3",hover:"#9e9c90",requiredDefault:"#5bc0de",requiredHover:"#38859c"},opacity:.7,size:{"default":{width:2440,height:1220,thickness:18}}},CuttingEdge:{width:5,
  strokeWidth:4},EdgeType:{v:"vertical",h:"horizontal"},MaxWorkNum:20,MinWorkNum:1,Canvas:{size:{width:1200,height:675}},CuttingBound:1,PreCuttingLength:12,LengthLabelInverseLimitLength:40};c.lastWorkNum=0;c.init=function(a,b){c.workId=a;var d=w();c.preCutting=d.preCutting;c.preCutting&&(b.width-=h.PreCuttingLength,b.height-=h.PreCuttingLength);c.woodSize=b;d.size=b;c.selectedEdge=null;c.stage&&c.stage.destroy();c.woodLayer&&c.woodLayer.destroy();c.interactionLayer&&c.interactionLayer.destroy();c.backLayer&&
  c.backLayer.destroy();var e=c.stage=new Konva.Stage({container:"main",width:h.Canvas.size.width,height:h.Canvas.size.height,fill:"white"});c.backLayer=new Konva.Layer({id:"back-layer"});e.add(c.backLayer);c.interactionLayer=new Konva.Layer({id:"interaction-layer"});e.add(c.interactionLayer);var f=c.scale=P(h.Canvas.size,b),g;if(g=d.getSavedNodes()){g=c.woodLayer=Konva.Node.create(g);e.add(g);e.find(".wood-group").each(function(a,b){L(a)});var k=e.find(".cutting-edge");k.each(function(a,b){I(a)});
  c.cuttingNum=k.length}else c.cuttingNum=0,g=c.woodLayer=new Konva.Layer({id:"wood-layer"}),e.add(g),k={x:(h.Canvas.size.width/f-b.width)/2,y:(h.Canvas.size.height/f-b.height)/2},k=E(k),k=A(k,b),g.add(k);k=ia(50,f);c.backLayer.add(k);g.scale({x:f,y:f});c.backLayer.scale({x:f,y:f});c.interactionLayer.moveToTop();c.preCutting?($("#wood-width").val(b.width+h.PreCuttingLength),$("#wood-height").val(b.height+h.PreCuttingLength)):($("#wood-width").val(b.width),$("#wood-height").val(b.height));$("#wood-thickness").val(b.thickness);
  $("#work-name").html(d.name);$("#pre-cutting").prop("checked",c.preCutting);var p=!1;$(".work-list-item").each(function(){var a=$(this);a.attr("work-id")===d.id?(a.addClass("active"),p=!0):a.removeClass("active")});p||(f=T(d),f.addClass("active"),$("#work-list").append(f));ha(c.stage);c.moveCanvasMode=!1;c.editCanvasMode=!1;e.draw()};$(document).ready(function(){$('[data-toggle="popover"]').popover();alertify.parent(document.body);alertify.logPosition("right");alertify.maxLogItems(3);alertify.delay(2E3);
  alertify.okBtn("\ud655\uc778");alertify.cancelBtn("\ucde8\uc18c");alertify.closeLogOnClick(!0);var a=M("width")||h.Wood.size["default"].width,b=M("height")||h.Wood.size["default"].height,d=M("thickness")||h.Wood.size["default"].thickness;a={width:Number(a),height:Number(b),thickness:Number(d)};c.defaultWoodSize=a;c.lastWorkNum++;b=new C("\ubaa9\ucde8\ub3c4"+c.lastWorkNum);r[b.id]=b;c.init(b.id,a);$("#main").focus();Z();aa()});$(window).on("beforeunload",function(){localStorage.clear()});Konva.Stage.prototype.getAdjustedPointerPosition=
  function(){var a=this.getPointerPosition();return{x:a.x-this.position().x,y:a.y-this.position().y}};Konva.Group.prototype.fillDefaultColor=function(){var a=this.getWood(),b=this.getAttr("required")?h.Wood.color.requiredDefault:h.Wood.color["default"];a.fill(b)};Konva.Group.prototype.fillActiveColor=function(){var a=this.getWood(),b=this.getAttr("required")?h.Wood.color.requiredHover:h.Wood.color.hover;a.fill(b)};Konva.Line.prototype.styleDefaultColor=function(){if(!this.hasName("cutting-edge"))throw Error("Only cutting edge can call styleDefaultColor function");
  this.stroke(null);this.shadowBlur(0)};Konva.Line.prototype.styleActiveColor=function(){if(!this.hasName("cutting-edge"))throw Error("Only cutting edge can call styleActiveColor function");this.stroke("lime");this.shadowBlur(5)};Konva.Group.prototype.verticalCut=function(a){var b=this.getWood();a={x:a.x/c.scale-this.x(),y:a.y/c.scale-this.y()};a=E(a);var d=this.position(),e={width:a.x,height:b.height()},f={x:this.x()+a.x+h.CuttingEdge.width,y:this.position().y},g={width:b.width()-a.x-h.CuttingEdge.width,
  height:b.height()};D(e)&&D(g)?(d=A(d,e),f=A(f,g),g={x:this.x()+a.x+h.CuttingEdge.width/2,y:this.position().y},b={x:this.x()+a.x+h.CuttingEdge.width/2,y:this.position().y+Number(b.height())},b=K(g,b),c.woodLayer.add(d).add(f).add(b),this.destroy(),c.woodLayer.find(".cutting-edge").each(function(a,b){a.moveToTop()}),c.woodLayer.draw(),c.cuttingNum+=1):J()};Konva.Group.prototype.horizontalCut=function(a){var b=this.getWood();a={x:a.x/c.scale-this.x(),y:a.y/c.scale-this.y()};a=E(a);var d=this.position(),
  e={width:b.width(),height:a.y},f={x:this.position().x,y:this.y()+a.y+h.CuttingEdge.width},g={width:b.width(),height:b.height()-a.y-h.CuttingEdge.width};D(e)&&D(g)?(d=A(d,e),f=A(f,g),g={x:this.position().x,y:this.y()+a.y+h.CuttingEdge.width/2},b={x:this.position().x+Number(b.width()),y:this.y()+a.y+h.CuttingEdge.width/2},b=K(g,b),c.woodLayer.add(d).add(f).add(b),this.destroy(),c.woodLayer.find(".cutting-edge").each(function(a,b){a.moveToTop()}),c.woodLayer.draw(),c.cuttingNum+=1):J()};Konva.Line.prototype.deleteEdge=
  function(){var a=h.EdgeType;if(!this.hasName("cutting-edge"))throw Error("Only cutting edge can call findAdjacentWoods function");var b=this.hasName("vertical-edge")?a.v:a.h;this.points();var d=this.findAllAdjacents(),e=d.woodGroups1,f=d.woodGroups2,g=d.edges1;d=d.edges2;if(1===e.length){var k=e[0];var p=k.getWood();k.position();b===a.v?(f.forEach(function(a){a.x(k.x());var b=a.getWood();b.width(p.width()+b.width()+h.CuttingEdge.width);a.updateLabels()}),d.forEach(function(a){var b=a.points();b[0]=
  k.x();a.points(b)})):(f.forEach(function(a){a.y(k.y());var b=a.getWood();b.height(p.height()+b.height()+h.CuttingEdge.width);a.updateLabels()}),d.forEach(function(a){var b=a.points();b[1]=k.y();a.points(b)}))}else if(1===f.length)k=f[0],p=k.getWood(),k.position(),b===a.v?(e.forEach(function(a){var b=a.getWood();b.width(p.width()+b.width()+h.CuttingEdge.width);a.updateLabels()}),g.forEach(function(a){var b=a.points();b[2]+=p.width()+h.CuttingEdge.width;a.points(b)})):(e.forEach(function(a){var b=a.getWood();
  b.height(p.height()+b.height()+h.CuttingEdge.width);a.updateLabels()}),g.forEach(function(a){var b=a.points();b[3]+=p.height()+h.CuttingEdge.width;a.points(b)}));else{alertify.error("\ucef7\ud305\uc758 \ud55c\ucabd \uba74\uc740 \ub2e8\uc77c \uba74\uc774 \ub418\uc5b4\uc788\uc5b4\uc57c \ud569\ub2c8\ub2e4.");return}k.destroy();this.destroy();c.woodLayer.draw();c.cuttingNum--};Konva.Line.prototype.findAllAdjacents=function(){var a=h.EdgeType;if(!this.hasName("cutting-edge"))throw Error("Only cutting edge can call findAdjacentWoods function");
  var b=this.hasName("vertical-edge")?a.v:a.h,d=this.points(),e=d[0],f=d[1],g=d[2],k=d[3],p=[],n=[];c.woodLayer.find(".wood-group").toArray().forEach(function(c){var d=c.getWood();b===a.v?c.y()>=f&&c.y()+Number(d.height())<=k&&(c.x()<=e&&Math.abs(c.x()+Number(d.width())-e)<=h.CuttingEdge.width?p.push(c):c.x()>e&&Math.abs(c.x()-e)<=h.CuttingEdge.width&&n.push(c)):c.x()>=e&&c.x()+Number(d.width())<=g&&(c.y()<=f&&Math.abs(c.y()+Number(d.height())-f)<=h.CuttingEdge.width?p.push(c):c.y()>f&&Math.abs(c.y()-
  f)<=h.CuttingEdge.width&&n.push(c))});var m=[],l=[];c.woodLayer.find(b===a.v?".horizontal-edge":".vertical-edge").toArray().forEach(function(c){var d=c.points(),n=d[0],p=d[1],q=d[2];d=d[3];b===a.v?p>f&&p<k&&(q<=e&&Math.abs(q-e)<=h.CuttingEdge.width?m.push(c):n>=e&&Math.abs(n-e)<=h.CuttingEdge.width&&l.push(c)):n>e&&n<g&&(d<=f&&Math.abs(d-f)<=h.CuttingEdge.width?m.push(c):p>=f&&Math.abs(p-f)<=h.CuttingEdge.width&&l.push(c))});return{woodGroups1:p,woodGroups2:n,edges1:m,edges2:l}};Konva.Group.prototype.updateLabels=
  function(){var a=this.getWood();this.find(".wood-label").each(function(a){a.destroy()});a=U(a);this.add(a.w).add(a.h)};Konva.Group.prototype.getWood=function(){var a=this.findOne(".wood");if(!a)throw this.destroy(),Error("Can not find wood");return a};Konva.Group.prototype.getCenterPosition=function(){var a=this.getWood();return{x:this.x()+a.width()/2,y:this.y()+a.height()/2}};Konva.Group.prototype.verticalDivide=function(a){var b=this,d=b.getWood(),e=Number(d.height()),f=b.y(),g=b.y()+e,k=0;a.forEach(function(d,
  n){var m=b.position();m.x+=k;var l={width:d,height:e};k+=d;m=A(m,l);c.woodLayer.add(m);n<a.length-1&&(m={x:b.x()+k+h.CuttingEdge.width/2,y:f},l={x:b.x()+k+h.CuttingEdge.width/2,y:g},k+=h.CuttingEdge.width,m=K(m,l),c.woodLayer.add(m))});this.destroy();c.woodLayer.find(".cutting-edge").each(function(a,b){a.moveToTop()});c.woodLayer.draw();c.cuttingNum+=a.length-1};Konva.Group.prototype.horizontalDivide=function(a){var b=this,d=b.getWood(),e=Number(d.width()),f=b.x(),g=b.x()+e,k=0;a.forEach(function(d,
  n){var m=b.position();m.y+=k;var l={width:e,height:d};k+=d;m=A(m,l);c.woodLayer.add(m);n<a.length-1&&(m={x:f,y:b.y()+k+h.CuttingEdge.width/2},l={x:g,y:b.y()+k+h.CuttingEdge.width/2},k+=h.CuttingEdge.width,m=K(m,l),c.woodLayer.add(m))});this.destroy();c.woodLayer.find(".cutting-edge").each(function(a,b){a.moveToTop()});c.woodLayer.draw();c.cuttingNum+=a.length-1};Konva.Line.prototype.isSelected=function(){return c.selectedEdge&&c.selectedEdge._id===this._id};Konva.Line.prototype.move1Step=function(a){var b=
  h.EdgeType,d=this.hasName("vertical-edge")?b.v:b.h,e=this.findAllAdjacents(),f=e.woodGroups1,g=e.woodGroups2,k=e.edges1;e=e.edges2;if(0<a){g.sort(function(a,c){if(d===b.v){var e=a.getWood(),f=c.getWood();return a.x()+e.width()-(c.x()+f.width())}e=a.getWood();f=c.getWood();return a.y()+e.height()-(c.y()+f.height())});var p=g[0].getWood()}else f.sort(function(a,c){return d===b.v?a.x()-c.x():a.y()-c.y()}),p=f[0].getWood();p=d===b.v?p.width():p.height();p=Number(p)-Math.abs(a);p>=h.CuttingBound?(d===
  b.v?(f.forEach(function(b,c){var d=b.getWood();d.width(d.width()+a);b.updateLabels()}),g.forEach(function(b,c){var d=b.getWood();d.width(d.width()-a);b.x(b.x()+a);b.updateLabels()}),k.forEach(function(b,c){var d=b.points();d[2]+=a;b.points(d)}),e.forEach(function(b,c){var d=b.points();d[0]+=a;b.points(d)}),f=this.points(),f[0]+=a,f[2]+=a,this.points(f)):(f.forEach(function(b,c){var d=b.getWood();d.height(d.height()+a);b.updateLabels()}),g.forEach(function(b,c){var d=b.getWood();d.height(d.height()-
  a);b.y(b.y()+a);b.updateLabels()}),k.forEach(function(b,c){var d=b.points();d[3]+=a;b.points(d)}),e.forEach(function(b,c){var d=b.points();d[1]+=a;b.points(d)}),f=this.points(),f[1]+=a,f[3]+=a,this.points(f)),c.woodLayer.draw(),ja(a,d)):J()};Object.prototype.watch||Object.defineProperty(Object.prototype,"watch",{enumerable:!1,configurable:!0,writable:!1,value:function(a,b){var c=this[a],e=c,f=function(){return e},g=function(d){c=e;return e=b.call(this,a,c,d)};delete this[a]&&Object.defineProperty(this,
  a,{get:f,set:g,enumerable:!0,configurable:!0})}});Object.prototype.unwatch||Object.defineProperty(Object.prototype,"unwatch",{enumerable:!1,configurable:!0,writable:!1,value:function(a){var b=this[a];delete this[a];this[a]=b}});Number.prototype.addThousandComma||(Number.prototype.addThousandComma=function(){var a=String(this),b=[],c,e=0;for(c=a.length-1;0<=c;c--)b.unshift(a[c]),2===e%3&&e!==a.length-1&&b.unshift(","),e++;return b.join("")});String.prototype.format||(String.prototype.format=function(){var a=
  this,b;for(b in arguments)a=a.replace("{"+b+"}",arguments[b]);return a})})(this);var testing=!0,browser="";